### PR TITLE
fix: Handle redirect URL containing a ':'

### PR DESCRIPTION
**Pull request by artonge**
Replace `parse_url` as it does not support path containing a `:`.

### CODE REVIEW

**Comment by julien-nc** [comment]
Can it happen with another character than ":"?

**Comment by artonge** [comment]
> Can it happen with another character than ":"?

Probably yes. But we don't have such reports for now.

Thinking about it, I don't think that my solution works, as in case of http://... The initial : will be replaced.

**Comment by artonge** [comment]
Updated to be more generic. This will remove the protocol and the domain name.

**Comment by julien-nc** [comment]
Can you check it does not break the login flow with the desktop client? That was an issue which was fixed by https://github.com/nextcloud/user_oidc/pull/971

**Pull request merged**
